### ISSUE TITLE
expression must have a pointer type instead of reference type

### ISSUE THREAD

**Issue by Abhimanyu10** [arjan-bal/competitive-coding-library#1]
Line 87 in the file segtree with pointers
```cpp
inline int query(int st, int en, pnode &cur, int l, int r)
{
	if(cur && cur->lazy) push(st, en, cur);
	if(st>r || en<l) return 0;
	if(!cur) return 0;
	if(st>=l && en<=r) return cur->val;
	int mid=((st+en)>>1);
	return query(st, mid, cur->l, l, r)+query(mid+1, en, cur->r, l, r);
}
```
pnode is passed as a  reference not as a pointer so -> operator can not be used to access the members.

**Comment by Abhimanyu10** [comment]
Same bug with rest of the snippets also .

**Comment by arjan-bal** [comment]
cur is a reference to a pointer. This is done so that we can modify the address cur is pointing to and it will be reflected in the calling function of query too. A similar situation to when we want to delete the head of a linked list inside a function (without returning a pointer). We can do that if we have a reference to the head pointer.
It should compile without any problems if pnode is defined as node*
